### ISSUE TITLE
no attribute 'disable'

### ISSUE THREAD

**Issue by michelvancan** [pimoroni/trilobot-python#32] opened 2022-03-25 13:16 UTC
What is explained does not work! When we execute:
git clone https://github.com/pimoroni/trilobot-python
cd trilobot-python
sudo ./install.sh
python flash_underlights.py
----> AttributeError: module 'sn3218' has no attribute 'disable'

I looked at the trilobot code and you are not using the class defined by sn3218 as object, and as the
disable function is missing, so we get the previous error.
So I replaced
	sn3218.disable()
by 
	sn3218._get_sn3218().disable()

It works, but this is not the right way to do it!!!

**Comment by ZodiusInfuser** [comment] 2022-03-29 10:30
Thanks for raising this. I believe our SN3218 library was updated recently, so sounds like the disable was hidden for some reason. I will check to see what happened and push a fix.

**Comment by kleewyck** [comment] 2022-04-09 16:55
I'm seeing the same issue too. The above fix worked for me also. Thanks!

**Comment by cloudmartin** [comment] 2022-06-11 18:39
I too am having the problem, and wasted a lot of time uninstalling and reinstalling!!!

**Comment by justanotherbyte** [comment] 2022-08-19 21:26
Any eta to when this issue will be fixed on this repo?

**Comment by ZodiusInfuser** [comment] 2022-08-22 13:12
Apologies to all of you for letting this slip! It has been on my list to get this sorted, but other tasks have kept getting in the way.

I have had the priority of this raised in our internal work schedule, so I hope to get to it either by the end of this week, or early next @justanotherbyte.

**Comment by ZodiusInfuser** [comment] 2022-08-23 15:58
I had chance today to fire up a fresh Trilobot and reproduce the issue. I can confirm that it is because of the 2.0.0 update to the SN3218 library, as initially I was running 1.2.7 and couldn't reproduce until I updated.
The fix is currently here: https://github.com/pimoroni/trilobot-python/pull/33.

Once it gets merged then you will be able to get it by doing:

```
git clone https://github.com/pimoroni/trilobot-python
cd trilobot-python
sudo ./install.sh --unstable
```

In the meantime you can do `pip install sn3218==1.2.7` to downgrade your library to work with the current Trilobot library.

**Comment by justanotherbyte** [comment] 2022-08-27 16:32
Awesome thanks 👍

**Comment by RowMur** [comment] 2023-01-28 22:42
Is there an update on this? I'm still having this issue...

**Comment by ZodiusInfuser** [comment] 2023-01-29 11:32
Hi @RowMur. Sorry, it seems I never merged the branch with the fix in! I'll merge it in now, then you can try doing:
```
git clone https://github.com/pimoroni/trilobot-python
cd trilobot-python
sudo ./install.sh --unstable
```

**Comment by christophh-tt** [comment] 2023-02-02 15:20
Hey @ZodiusInfuser unfortunally the issue seems not to be fixed on main branch. I need to checkout the 0.0.1 release tag and also manully install sn3218 in version 1.2.7.

**Comment by ZodiusInfuser** [comment] 2023-02-06 14:52
Hey @RowMur, @christophh-tt. I have set up a fresh Pi OS image today and followed our install instructions for Trilobot. Out of the box the examples work first time for me. This seems to be because it pulls down the v0.01 version of this library and the v1.2.7 of the sn3218 library. If I use Pip to upgrade the sn3218 library then the errors occur. Perhaps not may users have done this, hence the low number of reports of this issue? 🤔 

Carrying on, I tried following my own instructions from last week and Aug 23, 2022, of installing unstable, and that resulted in the same error of sn3218 complaining about the missing `disable()`. Checking the line number of the error revealed the issue to me. Even though the unstable v0.0.2 had been installed correctly (i.e. main branch), v0.0.1 was also installed and took priority.

Running `sudo ./install.sh --uninstall` removed the v0.0.1 for me, letting v0.0.2 work. Worth you two giving this a try.
In the meantime I will go ahead with raise a new release, so that people don't need to grab unstable in the future.

**Comment by RowMur** [comment] 2023-02-06 15:06
Great, thanks for the support. I'll give this another try.

**Comment by ZodiusInfuser** [comment] 2023-02-06 16:54
The 0.0.2 release is now live on PyPi and I have tested with a fresh `sudo ./install.sh`. Can also be pulled down with `pip install trilobot`

**Comment by IgnatiusB** [comment] 2023-02-12 13:33
I have just tried pip install trilobot but still getting errors:
steve@raspberrypi:~/Pimoroni/trilobot/examples $ python3 show_underlighting.py
Trilobot Example: Show Underlighting

Traceback (most recent call last):
  File "/home/steve/Pimoroni/trilobot/examples/show_underlighting.py", line 16, in <module>
    tbot = Trilobot()
  File "/usr/local/lib/python3.9/dist-packages/trilobot/__init__.py", line 134, in __init__
    self.sn3218 = sn3218.SN3218()
  File "/usr/local/lib/python3.9/dist-packages/sn3218/__init__.py", line 26, in __init__
    self.i2c = SMBus(i2c_bus)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function Trilobot.__del__ at 0x7f81c8b8b0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/trilobot/__init__.py", line 155, in __del__
    self.sn3218.disable()
AttributeError: 'Trilobot' object has no attribute 'sn3218'

**Comment by ZodiusInfuser** [comment] 2023-02-12 13:44
@IgnatiusB That error is because you need to enable the I2C bus on your Pi. It is not related to this issue.

You can find the instructions for doing this on the main page of this repo, but I have pasted them below too:


# Pre-requisites

You must enable:

* i2c: `sudo raspi-config nonint do_i2c 0`

You can optionally run `sudo raspi-config` or the graphical Raspberry Pi Configuration UI to enable interfaces.

**Comment by IgnatiusB** [comment] 2023-02-12 14:49
Thanks very much for your help. Everything working now.

Best wishes.

**Comment by Gadgetoid** [comment] 2024-04-24 18:40
Aha uh... sorry Chris, I very obviously caused this havoc 😬

Trilobot worked out the box for me, too, so I'll consider this complete!

**Closed by Gadgetoid** 2024-04-24 18:40 UTC
